# Generated by Django 5.1.1 on 2024-10-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='achievements',
        ),
        migrations.AlterUniqueTogether(
            name='achievementemployee',
            unique_together={('achievement', 'employee', 'achievement_date')},
        ),
    ]
